package com.gusortiz.sitioweb;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/biografia")
public class BiografiaServlet extends HttpServlet {
    
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        
        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"es\">");
        out.println("<head>");
        out.println("    <meta charset=\"UTF-8\">");
        out.println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        out.println("    <title>Mi Biografía - Sitio Personal</title>");
        out.println("    <style>");
        out.println("        body {");
        out.println("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
        out.println("            line-height: 1.6;");
        out.println("            margin: 0;");
        out.println("            padding: 0;");
        out.println("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);");
        out.println("            min-height: 100vh;");
        out.println("        }");
        out.println("        .container {");
        out.println("            max-width: 1200px;");
        out.println("            margin: 0 auto;");
        out.println("            padding: 20px;");
        out.println("        }");
        out.println("        .header {");
        out.println("            background: rgba(255, 255, 255, 0.95);");
        out.println("            padding: 20px;");
        out.println("            border-radius: 15px;");
        out.println("            margin-bottom: 30px;");
        out.println("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);");
        out.println("            backdrop-filter: blur(10px);");
        out.println("        }");
        out.println("        .nav {");
        out.println("            text-align: center;");
        out.println("            margin-bottom: 20px;");
        out.println("        }");
        out.println("        .nav a {");
        out.println("            display: inline-block;");
        out.println("            margin: 0 15px;");
        out.println("            padding: 10px 20px;");
        out.println("            text-decoration: none;");
        out.println("            color: #667eea;");
        out.println("            background: rgba(102, 126, 234, 0.1);");
        out.println("            border-radius: 25px;");
        out.println("            transition: all 0.3s ease;");
        out.println("        }");
        out.println("        .nav a:hover {");
        out.println("            background: #667eea;");
        out.println("            color: white;");
        out.println("            transform: translateY(-2px);");
        out.println("        }");
        out.println("        .profile-section {");
        out.println("            background: rgba(255, 255, 255, 0.95);");
        out.println("            padding: 30px;");
        out.println("            border-radius: 15px;");
        out.println("            margin-bottom: 30px;");
        out.println("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);");
        out.println("            backdrop-filter: blur(10px);");
        out.println("        }");
        out.println("        .profile-header {");
        out.println("            text-align: center;");
        out.println("            margin-bottom: 30px;");
        out.println("        }");
        out.println("        .profile-photo {");
        out.println("            width: 200px;");
        out.println("            height: 200px;");
        out.println("            border-radius: 50%;");
        out.println("            object-fit: cover;");
        out.println("            border: 5px solid #667eea;");
        out.println("            margin-bottom: 20px;");
        out.println("            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);");
        out.println("        }");
        out.println("        .profile-name {");
        out.println("            font-size: 2.5em;");
        out.println("            color: #333;");
        out.println("            margin-bottom: 10px;");
        out.println("        }");
        out.println("        .profile-age {");
        out.println("            font-size: 1.2em;");
        out.println("            color: #666;");
        out.println("            margin-bottom: 20px;");
        out.println("        }");
        out.println("        .info-grid {");
        out.println("            display: grid;");
        out.println("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));");
        out.println("            gap: 20px;");
        out.println("            margin-top: 30px;");
        out.println("        }");
        out.println("        .info-card {");
        out.println("            background: rgba(255, 255, 255, 0.8);");
        out.println("            padding: 20px;");
        out.println("            border-radius: 10px;");
        out.println("            border-left: 4px solid #667eea;");
        out.println("        }");
        out.println("        .info-card h3 {");
        out.println("            color: #667eea;");
        out.println("            margin-top: 0;");
        out.println("            border-bottom: 2px solid #f0f0f0;");
        out.println("            padding-bottom: 10px;");
        out.println("        }");
        out.println("        .info-card ul {");
        out.println("            list-style: none;");
        out.println("            padding: 0;");
        out.println("        }");
        out.println("        .info-card li {");
        out.println("            padding: 5px 0;");
        out.println("            border-bottom: 1px solid #f0f0f0;");
        out.println("        }");
        out.println("        .info-card li:last-child {");
        out.println("            border-bottom: none;");
        out.println("        }");
        out.println("        @media (max-width: 768px) {");
        out.println("            .info-grid {");
        out.println("                grid-template-columns: 1fr;");
        out.println("            }");
        out.println("            .profile-photo {");
        out.println("                width: 150px;");
        out.println("                height: 150px;");
        out.println("            }");
        out.println("        }");
        out.println("    </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("    <div class=\"container\">");
        out.println("        <div class=\"header\">");
        out.println("            <div class=\"nav\">");
        out.println("                <a href=\"index.html\">Inicio</a>");
        out.println("                <a href=\"biografia\">Biografía</a>");
        out.println("                <a href=\"temas-interes\">Temas de Interés</a>");
        out.println("            </div>");
        out.println("        </div>");
        out.println("        ");
        out.println("        <div class=\"profile-section\">");
        out.println("            <div class=\"profile-header\">");
        out.println("                <img src=\"img/mi-foto.jpg\" alt=\"Mi Foto\" class=\"profile-photo\">");
        out.println("                <h1 class=\"profile-name\">Gustavo Ortiz</h1>");
        out.println("                <p class=\"profile-age\">22 años - Estudiante de Ingeniería de Sistemas</p>");
        out.println("            </div>");
        out.println("            ");
        out.println("            <div class=\"info-grid\">");
        out.println("                <div class=\"info-card\">");
        out.println("                    <h3>🎯 Objetivos Académicos</h3>");
        out.println("                    <ul>");
        out.println("                        <li>Completar la carrera de Ingeniería de Sistemas</li>");
        out.println("                        <li>Especializarme en desarrollo web y aplicaciones móviles</li>");
        out.println("                        <li>Obtener certificaciones en tecnologías modernas</li>");
        out.println("                        <li>Participar en proyectos de investigación tecnológica</li>");
        out.println("                    </ul>");
        out.println("                </div>");
        out.println("                ");
        out.println("                <div class=\"info-card\">");
        out.println("                    <h3>🎮 Pasatiempos</h3>");
        out.println("                    <ul>");
        out.println("                        <li>Desarrollo de videojuegos indie</li>");
        out.println("                        <li>Programación en Python y Java</li>");
        out.println("                        <li>Jugar videojuegos de estrategia</li>");
        out.println("                    </ul>");
        out.println("                </div>");
        out.println("                ");
        out.println("                <div class=\"info-card\">");
        out.println("                    <h3>💻 Intereses Tecnológicos</h3>");
        out.println("                    <ul>");
        out.println("                        <li>Inteligencia Artificial y Machine Learning</li>");
        out.println("                        <li>Desarrollo de aplicaciones web modernas</li>");
        out.println("                        <li>Arquitectura de software y patrones de diseño</li>");
        out.println("                        <li>Seguridad informática y ciberseguridad</li>");
        out.println("                    </ul>");
        out.println("                </div>");
        out.println("                ");
        out.println("                <div class=\"info-card\">");
        out.println("                    <h3>🎵 Gustos Personales</h3>");
        out.println("                    <ul>");
        out.println("                        <li>Música electrónica y rock alternativo</li>");
        out.println("                        <li>Películas de ciencia ficción y thriller</li>");
        out.println("                        <li>Libros de tecnología y ciencia</li>");
        out.println("                        <li>Cocina internacional y experimentar con recetas</li>");
        out.println("                    </ul>");
        out.println("                </div>");
        out.println("            </div>");
        out.println("        </div>");
        out.println("    </div>");
        out.println("</body>");
        out.println("</html>");
        
        out.close();
    }
}
