package com.gusortiz.sitioweb;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/temas-interes")
public class TemasInteresServlet extends HttpServlet {
    
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        
        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"es\">");
        out.println("<head>");
        out.println("    <meta charset=\"UTF-8\">");
        out.println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        out.println("    <title>Temas de Interés - Sitio Personal</title>");
        out.println("    <style>");
        out.println("        body {");
        out.println("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
        out.println("            line-height: 1.6;");
        out.println("            margin: 0;");
        out.println("            padding: 0;");
        out.println("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);");
        out.println("            min-height: 100vh;");
        out.println("        }");
        out.println("        .container {");
        out.println("            max-width: 1200px;");
        out.println("            margin: 0 auto;");
        out.println("            padding: 20px;");
        out.println("        }");
        out.println("        .header {");
        out.println("            background: rgba(255, 255, 255, 0.95);");
        out.println("            padding: 20px;");
        out.println("            border-radius: 15px;");
        out.println("            margin-bottom: 30px;");
        out.println("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);");
        out.println("            backdrop-filter: blur(10px);");
        out.println("        }");
        out.println("        .nav {");
        out.println("            text-align: center;");
        out.println("            margin-bottom: 20px;");
        out.println("        }");
        out.println("        .nav a {");
        out.println("            display: inline-block;");
        out.println("            margin: 0 15px;");
        out.println("            padding: 10px 20px;");
        out.println("            text-decoration: none;");
        out.println("            color: #667eea;");
        out.println("            background: rgba(102, 126, 234, 0.1);");
        out.println("            border-radius: 25px;");
        out.println("            transition: all 0.3s ease;");
        out.println("        }");
        out.println("        .nav a:hover {");
        out.println("            background: #667eea;");
        out.println("            color: white;");
        out.println("            transform: translateY(-2px);");
        out.println("        }");
        out.println("        .content-section {");
        out.println("            background: rgba(255, 255, 255, 0.95);");
        out.println("            padding: 30px;");
        out.println("            border-radius: 15px;");
        out.println("            margin-bottom: 30px;");
        out.println("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);");
        out.println("            backdrop-filter: blur(10px);");
        out.println("        }");
        out.println("        .main-title {");
        out.println("            text-align: center;");
        out.println("            color: #333;");
        out.println("            font-size: 2.5em;");
        out.println("            margin-bottom: 30px;");
        out.println("            border-bottom: 3px solid #667eea;");
        out.println("            padding-bottom: 15px;");
        out.println("        }");
        out.println("        .topic-section {");
        out.println("            margin-bottom: 40px;");
        out.println("            padding: 20px;");
        out.println("            background: rgba(255, 255, 255, 0.8);");
        out.println("            border-radius: 10px;");
        out.println("            border-left: 4px solid #667eea;");
        out.println("        }");
        out.println("        .topic-section h2 {");
        out.println("            color: #667eea;");
        out.println("            font-size: 1.8em;");
        out.println("            margin-bottom: 15px;");
        out.println("        }");
        out.println("        .topic-section p {");
        out.println("            margin-bottom: 15px;");
        out.println("            text-align: justify;");
        out.println("            color: #444;");
        out.println("        }");
        out.println("        .topic-section img {");
        out.println("            max-width: 100%;");
        out.println("            height: auto;");
        out.println("            border-radius: 10px;");
        out.println("            margin: 20px 0;");
        out.println("            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);");
        out.println("        }");
        out.println("        .image-container {");
        out.println("            text-align: center;");
        out.println("            margin: 20px 0;");
        out.println("        }");
        out.println("        .image-caption {");
        out.println("            font-style: italic;");
        out.println("            color: #666;");
        out.println("            margin-top: 10px;");
        out.println("        }");
        out.println("        .links-section {");
        out.println("            background: rgba(102, 126, 234, 0.1);");
        out.println("            padding: 20px;");
        out.println("            border-radius: 10px;");
        out.println("            margin-top: 20px;");
        out.println("        }");
        out.println("        .links-section h3 {");
        out.println("            color: #667eea;");
        out.println("            margin-bottom: 15px;");
        out.println("        }");
        out.println("        .links-section a {");
        out.println("            display: inline-block;");
        out.println("            margin: 5px 10px 5px 0;");
        out.println("            padding: 8px 16px;");
        out.println("            background: #667eea;");
        out.println("            color: white;");
        out.println("            text-decoration: none;");
        out.println("            border-radius: 20px;");
        out.println("            transition: all 0.3s ease;");
        out.println("        }");
        out.println("        .links-section a:hover {");
        out.println("            background: #5a6fd8;");
        out.println("            transform: translateY(-2px);");
        out.println("        }");
        out.println("        .highlight {");
        out.println("            background: linear-gradient(120deg, #a8edea 0%, #fed6e3 100%);");
        out.println("            padding: 15px;");
        out.println("            border-radius: 8px;");
        out.println("            margin: 20px 0;");
        out.println("            border-left: 4px solid #667eea;");
        out.println("        }");
        out.println("        @media (max-width: 768px) {");
        out.println("            .main-title {");
        out.println("                font-size: 2em;");
        out.println("            }");
        out.println("            .topic-section {");
        out.println("                padding: 15px;");
        out.println("            }");
        out.println("        }");
        out.println("    </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("    <div class=\"container\">");
        out.println("        <div class=\"header\">");
        out.println("            <div class=\"nav\">");
        out.println("                <a href=\"index.html\">Inicio</a>");
        out.println("                <a href=\"biografia\">Biografía</a>");
        out.println("                <a href=\"temas-interes\">Temas de Interés</a>");
        out.println("            </div>");
        out.println("        </div>");
        out.println("        ");
        out.println("        <div class=\"content-section\">");
        out.println("            <h1 class=\"main-title\">🚀 Tecnologías Emergentes y el Futuro del Desarrollo</h1>");
        out.println("            ");
        out.println("            <div class=\"topic-section\">");
        out.println("                <h2>🤖 Inteligencia Artificial y Machine Learning</h2>");
        out.println("                <p>La inteligencia artificial está transformando radicalmente la forma en que desarrollamos software. Los modelos de lenguaje como GPT-4, Claude y otros están revolucionando la programación, permitiendo a los desarrolladores escribir código más rápido y eficiente.</p>");
        out.println("                <p>El machine learning está siendo aplicado en áreas como detección de bugs, optimización de código, y generación automática de documentación. Esto está creando nuevas oportunidades para los desarrolladores que entiendan cómo integrar estas tecnologías en sus aplicaciones.</p>");
        out.println("                <div class=\"image-container\">");
        out.println("                    <img src=\"img/ai-ml.jpg\" alt=\"Inteligencia Artificial y Machine Learning\" style=\"max-width: 500px;\">");
        out.println("                    <p class=\"image-caption\">Representación visual de redes neuronales y algoritmos de ML</p>");
        out.println("                </div>");
        out.println("            </div>");
        out.println("            ");
        out.println("            <div class=\"topic-section\">");
        out.println("                <h2>🌐 Desarrollo Web Moderno</h2>");
        out.println("                <p>El desarrollo web ha evolucionado significativamente en los últimos años. Frameworks como React, Vue.js y Angular han cambiado la forma en que construimos interfaces de usuario, mientras que tecnologías como WebAssembly están permitiendo ejecutar código de alto rendimiento directamente en el navegador.</p>");
        out.println("                <p>La arquitectura de microservicios y las APIs RESTful/GraphQL están redefiniendo cómo se construyen las aplicaciones web escalables. Además, el desarrollo progresivo de aplicaciones web (PWA) está cerrando la brecha entre aplicaciones web y móviles nativas.</p>");
        out.println("                <div class=\"highlight\">");
        out.println("                    <strong>💡 Dato interesante:</strong> Las PWAs pueden funcionar offline, enviar notificaciones push y ser instaladas en dispositivos móviles, todo desde el navegador web.");
        out.println("                </div>");
        out.println("            </div>");
        out.println("            ");
        out.println("            <div class=\"topic-section\">");
        out.println("                <h2>📱 Desarrollo Móvil y Cross-Platform</h2>");
        out.println("                <p>El desarrollo móvil está experimentando una revolución con frameworks como Flutter y React Native, que permiten crear aplicaciones nativas para múltiples plataformas desde un solo código base. Esto está democratizando el desarrollo móvil y reduciendo significativamente los costos de desarrollo.</p>");
        out.println("                <p>Kotlin para Android y Swift para iOS están evolucionando constantemente, ofreciendo características modernas como programación funcional, corrutinas y programación reactiva. Estas mejoras están haciendo que el desarrollo móvil sea más eficiente y menos propenso a errores.</p>");
        out.println("                <div class=\"image-container\">");
        out.println("                    <img src=\"img/mobile-dev.jpg\" alt=\"Desarrollo Móvil Cross-Platform\" style=\"max-width: 500px;\">");
        out.println("                    <p class=\"image-caption\">Desarrollo de aplicaciones móviles multiplataforma</p>");
        out.println("                </div>");
        out.println("            </div>");
        out.println("            ");
        out.println("            <div class=\"topic-section\">");
        out.println("                <h2>☁️ Computación en la Nube y DevOps</h2>");
        out.println("                <p>La computación en la nube ha transformado la infraestructura de TI, permitiendo a las empresas escalar rápidamente sin grandes inversiones en hardware. Plataformas como AWS, Azure y Google Cloud están ofreciendo servicios cada vez más sofisticados, desde contenedores hasta funciones serverless.</p>");
        out.println("                <p>DevOps y CI/CD están cambiando la cultura de desarrollo, promoviendo la colaboración entre desarrolladores y operaciones. Herramientas como Docker, Kubernetes, Jenkins y GitHub Actions están automatizando el proceso de desarrollo, testing y despliegue.</p>");
        out.println("            </div>");
        out.println("            ");
        out.println("            <div class=\"links-section\">");
        out.println("                <h3>🔗 Recursos Recomendados</h3>");
        out.println("                <a href=\"https://www.tensorflow.org/\" target=\"_blank\">TensorFlow - ML Framework</a>");
        out.println("                <a href=\"https://reactjs.org/\" target=\"_blank\">React - Biblioteca JavaScript</a>");
        out.println("                <a href=\"https://flutter.dev/\" target=\"_blank\">Flutter - Desarrollo Móvil</a>");
        out.println("                <a href=\"https://kubernetes.io/\" target=\"_blank\">Kubernetes - Orquestación</a>");
        out.println("                <a href=\"https://aws.amazon.com/\" target=\"_blank\">AWS - Computación en la Nube</a>");
        out.println("            </div>");
        out.println("        </div>");
        out.println("    </div>");
        out.println("</body>");
        out.println("</html>");
        
        out.close();
    }
}
